project_title: 'AWIPS II'
project_author: Unidata
baseurl: /awips2

markdown: kramdown
highlighter: true
lsi: false
safe: false
add_permalinks: true # adds permalinks to heading tags.

#Define permalink structure if you're using _posts.
#permalink: /news/:year/:month/:day/:title.html

exclude: ["node_modules", "sass", "README.md",
          "Gruntfile.js", "package.json", "config.rb", "bower.json",
          "Gemfile", "Gemfile.lock", "deploy.sh"]

kramdown:
  toc_levels: 1..3
  #auto_ids: true

  #input: GFM # enable github flavored markdown
  # use_coderay: true
  # coderay:
  #   coderay_line_numbers: nil
  #   coderay_css: style

